export const INSTR_SIZES: Record<string, number> = {
  'NOP': 1,
  'LXI': 3,
  'STAX': 1, 'LDAX': 1,
  'SHLD': 3, 'LHLD': 3,
  'STA': 3, 'LDA': 3,
  'INX': 1, 'DCX': 1, 'INR': 1, 'DCR': 1,
  'MVI': 2,
  'RLC': 1, 'RAL': 1, 'DAA': 1, 'STC': 1,
  'DAD': 1,
  'RRC': 1, 'RAR': 1, 'CMA': 1, 'CMC': 1,
  'MOV': 1,
  'HLT': 1,
  'ADD': 1, 'ADC': 1,
  'SUB': 1, 'SBB': 1,
  'ANA': 1, 'XRA': 1,
  'ORA': 1, 'CMP': 1,
  'RNZ': 1, 'RNC': 1, 'RPO': 1, 'RP': 1,
  'POP': 1, 'PUSH': 1,
  'JNZ': 3, 'JNC': 3, 'JPO': 3, 'JP': 3,
  'JMP': 3, 'OUT': 2, 'XTHL': 1, 'DI': 1,
  'CNZ': 3, 'CNC': 3, 'CPO': 3, 'CP': 3,
  'ADI': 2, 'SUI': 2, 'ANI': 2, 'ORI': 2,
  'RST': 1,
  'RZ': 1, 'RC': 1, 'RPE': 1, 'RM': 1,
  'RET': 1, 'PCHL': 1, 'SPHL': 1,
  'JZ': 3, 'JC': 3, 'JPE': 3, 'JM': 3,
  'IN': 2, 'XCHG': 1, 'EI': 1,
  'CZ': 3, 'CC': 3, 'CPE': 3, 'CM': 3,
  'CALL': 3,
  'ACI': 2, 'SBI': 2, 'XRI': 2, 'CPI': 2,
}